# Generated by Django 4.0.4 on 2022-04-25 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='article',
            name='date_added',
            field=models.TextField(blank=True),
        ),
    ]
