# Generated by Django 4.0.4 on 2022-04-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0002_remove_article_creation_date_article_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
