# Generated by Django 4.0.4 on 2022-04-25 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0003_alter_article_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='date_added',
            new_name='creation_date',
        ),
    ]
