# Generated by Django 4.0.4 on 2022-04-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0004_rename_date_added_article_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail_url',
            field=models.TextField(null=True),
        ),
    ]
