# Generated by Django 4.0.4 on 2022-04-25 09:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogs', '0005_article_article_tags_article_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='visibility',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=models.CharField(blank=True,
                                   help_text='Add or change tags (up to 5) so readers know what your article is about.',
                                   max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=ckeditor.fields.RichTextField(error_messages={'required': 'Please write something to post.'},
                                                help_text="Learn <a target='_blank' href='https://bit.ly/3K8H7F7'>How to write a blog?</a>"),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail_url',
            field=models.URLField(blank=True,
                                  help_text='Upload your image on any cloud and paste the link on this field.',
                                  null=True, verbose_name='Featured Image URL'),
        ),
    ]
