# Generated by Django 4.0.4 on 2022-04-26 09:24

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blogs', '0007_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=taggit.managers.TaggableManager(blank=True,
                                                  help_text='Add or change tags (up to 5) so readers know what your article is about.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
