# Generated by Django 4.0.4 on 2022-04-26 13:16

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('blogs', '0008_remove_article_article_tags_article_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_tags',
            field=taggit.managers.TaggableManager(blank=True,
                                                  help_text='Add a comma-separated list of tags (up to 5), so readers know what your article is about.',
                                                  through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='article',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
